### ISSUE TITLE
Reveal multiple cards

### ISSUE THREAD

**Issue by Paul2708** [TiredGoa1/Website-about-Leipzig#3]
Hey,

Currently, it is possible to reveal multiple cards in the same "time interval" before the cards will hide again.
So, the last card will stay shown if you click fast enough on three cards.

I think only two cards should be clickable before hiding the cards again to avoid these effects.

**Comment by TiredGoa1** [comment]
Hello, 

I think I have solved the problem. Would you perhaps test it briefly and give me some feedback?

**Comment by Paul2708** [comment]
I cannot reproduce the error, so it should be fixed! :)
However, you can still click on cards if you reveal a pair first. Compared to the initial bug report, the cards don't stay revealed and hide again.
